### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by NightMare646** [catppuccin/cava#6]
Error loading config. Only 'ncurses' output method supports HTML colors. Please change the colours or the output method.
As of version 0.7.0 ncurses is no longer the default output method
Gradient color 1 is invalid. It must be HTML color of the form '#xxxxxx'.

someone help me

**Comment by ahaseros** [comment]
Similar issue, solved by adding the following to `.config/cava/config`

[output]
method = ncurses

**Comment by NightMare646** [comment]
Thx
